version: "3.6"
services:
  hello:
    environment:
      - "REDISURL=redis:6379"
    image: "hello-world-http:latest"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379/tcp"
